project:
  output-dir: docs
  type: website
  render:
  - index.qmd
  - AI101/AI101WithNotes.qmd
  - AI101/AI101NoNotes.qmd
  - AIPolicyWriting/AIPolicyWritingNoNotes.qmd
  - AIPolicyWriting/AIPolicyWritingNonIncremental.qmd
  - AIPolicyWriting/AIPolicyWritingWithNotes.qmd

bibliography: commonFiles/references.bib  
csl: commonFiles/chicago-notes-intext-bibliography-access-dates.csl

profile:
  default: prod

format: 
  html:
    theme: commonFiles/custom.scss
    css: commonFiles/custom.css
    embed-resources: true   
    logo: assets/ETDDLogo.svg
  revealjs:
    revealjs-plugins:
      - a11y
    theme: commonFiles/custom.scss
    css: commonFiles/custom.css
    incremental: true
    reference-location: document
    slide-number: true
    show-slide-number: print
    embed-resources: true   
    subtitle: "What you need to know"
    fragment-in-url: true
    pdf-separate-fragments: true
    author-meta: "Killian Cimino"
    logo:
      path: assets/ETDDLogo.svg
      alt: "etdd logo"


