project:
  output-dir: docs
  type: website

bibliography: commonFiles/references.bib  
csl: commonFiles/chicago-notes-intext-bibliography-access-dates.csl

profile:
  default: dev

format: 
  html:
    theme: commonFiles/custom.scss
    css: commonFiles/custom.css
    embed-resources: true   
    logo: assets/ETDDLogo.svg
  revealjs:
    revealjs-plugins:
      - a11y
    theme: commonFiles/custom.scss
    css: commonFiles/custom.css
    incremental: true
    reference-location: document
    slide-number: true
    show-slide-number: print
    show-notes: true
    embed-resources: true   
    subtitle: "What you need to know"
    fragment-in-url: true
    pdf-separate-fragments: true
    author-meta: "Killian Cimino"
    logo:
      path: assets/ETDDLogo.svg
      alt: "etdd logo"


